### ISSUE TITLE
At least two locations where `course-content` is hardcoded as target repo

### ISSUE THREAD

**Issue by mwaskom** [NeuromatchAcademy/nmaci#10]
- https://github.com/NeuromatchAcademy/nmaci/blob/main/scripts/process_notebooks.py#L430
- https://github.com/NeuromatchAcademy/nmaci/blob/main/scripts/make_pr_comment.py#L82

This causes problems for colab badges created for DL.

**Comment by spirosChv** [comment]
problems for colab badges solved by adding an abstract name for repo name, instead of the hardcoded one ('course-content')
