### ISSUE TITLE
make primary branch name configurable

### ISSUE THREAD

**Issue by bgalbraith** [NeuromatchAcademy/nmaci#5]
We should separate out the repo name and main branch as config options. NMA's course-content repo still uses `master` as the primary branch name, while the github default is now `main`, and so the steps used in process_notebooks.py to rename branches will break on newer repos.

**Comment by mwaskom** [comment]
Makes sense.

My suggestion would be to define it as a global variable at the top of `process_notebooks.py` and configure it by reading from `os.environ`.

Then the workflow yamls would need to be updated to set that. (I guess you could be clever and set it dynamically in the workflow scripts by using metadata about the branch the pull request is against. Not sure if that's necessary.)

Implementing this will introduce conflicts with the work in #3.
